// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.startupRolloutPrefs.geo.provider.use_gpsd", true);
user_pref("app.normandy.user_id", "740bdb00-927c-4eee-b681-da96b1fb529f");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1567531250);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1567531370);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1567605207);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1567605447);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1567605327);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1567531130);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1567445210);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1567531490);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 737280);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.impressionId", "{faaabc74-f1a4-45a8-8c14-e0d235e4b60f}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1565758800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1567605955159");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1567607741159");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1567604122973");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1567607722973");
user_pref("browser.search.region", "CO");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181209160329");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1567605183");
user_pref("browser.startup.homepage_override.buildID", "20181209160329");
user_pref("browser.startup.homepage_override.mstone", "64.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\",\"webide-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Yahoo");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "64.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("dom.push.userAgentID", "2699e63d0dd64fb49873d66d49e1de3c");
user_pref("extensions.blocklist.lastModified", "Wed, 28 Aug 2019 19:55:12 GMT");
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 6);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1567531250);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181209160329");
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pocket.settings.test.panelSignUp", "control");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"4a9c1536-78da-4b8b-be73-cbce619150a3\",\"screenshots@mozilla.org\":\"f50f00fc-5656-4ec3-bb87-2ccd68222524\",\"webcompat-reporter@mozilla.org\":\"1aea8817-f1a6-4f3e-bfa0-9fb2b27d90de\",\"webcompat@mozilla.org\":\"23309fbd-5dca-4228-91fd-8a587d930612\",\"baidu-code-update@mozillaonline.com\":\"fa523bc1-ef48-49a7-849e-13769c95e547\",\"fxmonitor@mozilla.org\":\"4a1e342c-9056-41b2-9ea5-3c9385a94c2d\"}");
user_pref("idle.lastDailyNotification", 1567530980);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1565621426);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181209160329");
user_pref("media.gmp-manager.lastCheck", 1567605242);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1567444504);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "a11c6ba1-6cea-402c-ab05-3b006f009f14");
user_pref("security.sandbox.plugin.tempDirSuffix", "ea75436b-b91d-4a39-afe9-0c662ee9acda");
user_pref("services.blocklist.addons.checked", 1567531408);
user_pref("services.blocklist.gfx.checked", 1567531408);
user_pref("services.blocklist.onecrl.checked", 1567531408);
user_pref("services.blocklist.pinning.checked", 1567531408);
user_pref("services.blocklist.plugins.checked", 1567531408);
user_pref("services.settings.clock_skew_seconds", -279);
user_pref("services.settings.last_update_seconds", 1567531408);
user_pref("services.settings.main.language-dictionaries.last_check", 1567531408);
user_pref("services.settings.main.onboarding.last_check", 1565790612);
user_pref("services.settings.main.sites-classification.last_check", 1567531408);
user_pref("services.settings.main.tippytop.last_check", 1567531408);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1565621843);
user_pref("toolkit.startup.last_success", 1567605176);
user_pref("toolkit.telemetry.cachedClientID", "fdce848d-98eb-4f4e-9610-7fc5207309d8");
user_pref("toolkit.telemetry.previousBuildID", "20181209160329");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
